/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface AFHTTPBodyPart : NSObject <NSCopying> {
    id  _body;
    unsigned long long  _bodyContentLength;
    NSString * _boundary;
    bool  _hasFinalBoundary;
    bool  _hasInitialBoundary;
    NSDictionary * _headers;
    NSInputStream * _inputStream;
    int  _phase;
    unsigned long long  _phaseReadOffset;
    unsigned long long  _stringEncoding;
}

@property (nonatomic, readwrite, retain) id body;
@property (nonatomic, readwrite) unsigned long long bodyContentLength;
@property (nonatomic, readwrite, copy) NSString *boundary;
@property (getter=hasBytesAvailable, nonatomic, readonly) bool bytesAvailable;
@property (nonatomic, readonly) unsigned long long contentLength;
@property (nonatomic, readwrite) bool hasFinalBoundary;
@property (nonatomic, readwrite) bool hasInitialBoundary;
@property (nonatomic, readwrite, retain) NSDictionary *headers;
@property (nonatomic, readwrite, retain) NSInputStream *inputStream;
@property (nonatomic, readwrite) unsigned long long stringEncoding;

- (void).cxx_destruct;
- (id)body;
- (unsigned long long)bodyContentLength;
- (id)boundary;
- (unsigned long long)contentLength;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (bool)hasBytesAvailable;
- (bool)hasFinalBoundary;
- (bool)hasInitialBoundary;
- (id)headers;
- (id)init;
- (id)inputStream;
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;
- (long long)readData:(id)arg1 intoBuffer:(char *)arg2 maxLength:(unsigned long long)arg3;
- (void)setBody:(id)arg1;
- (void)setBodyContentLength:(unsigned long long)arg1;
- (void)setBoundary:(id)arg1;
- (void)setHasFinalBoundary:(bool)arg1;
- (void)setHasInitialBoundary:(bool)arg1;
- (void)setHeaders:(id)arg1;
- (void)setInputStream:(id)arg1;
- (void)setStringEncoding:(unsigned long long)arg1;
- (unsigned long long)stringEncoding;
- (id)stringForHeaders;
- (bool)transitionToNextPhase;

@end
