/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface AFHTTPClient : NSObject <NSCoding, NSCopying> {
    bool  _allowsInvalidSSLCertificate;
    NSURL * _baseURL;
    NSURLCredential * _defaultCredential;
    NSMutableDictionary * _defaultHeaders;
    int  _defaultSSLPinningMode;
    struct __SCNetworkReachability { } * _networkReachability;
    int  _networkReachabilityStatus;
    id  _networkReachabilityStatusBlock;
    NSOperationQueue * _operationQueue;
    int  _parameterEncoding;
    NSMutableArray * _registeredHTTPOperationClassNames;
    unsigned long long  _stringEncoding;
}

@property (nonatomic, readwrite) bool allowsInvalidSSLCertificate;
@property (nonatomic, readwrite, retain) NSURL *baseURL;
@property (nonatomic, readwrite, retain) NSURLCredential *defaultCredential;
@property (nonatomic, readwrite, retain) NSMutableDictionary *defaultHeaders;
@property (nonatomic, readwrite) int defaultSSLPinningMode;
@property (nonatomic, readwrite) struct __SCNetworkReachability { }*networkReachability;
@property (nonatomic, readwrite) int networkReachabilityStatus;
@property (nonatomic, readwrite, copy) id networkReachabilityStatusBlock;
@property (nonatomic, readwrite, retain) NSOperationQueue *operationQueue;
@property (nonatomic, readwrite) int parameterEncoding;
@property (nonatomic, readwrite, retain) NSMutableArray *registeredHTTPOperationClassNames;
@property (nonatomic, readwrite) unsigned long long stringEncoding;

+ (id)clientWithBaseURL:(id)arg1;

- (void).cxx_destruct;
- (id)HTTPRequestOperationWithRequest:(id)arg1 success:(id)arg2 failure:(id)arg3;
- (bool)allowsInvalidSSLCertificate;
- (id)baseURL;
- (void)cancelAllHTTPOperationsWithMethod:(id)arg1 path:(id)arg2;
- (void)clearAuthorizationHeader;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)defaultCredential;
- (id)defaultHeaders;
- (int)defaultSSLPinningMode;
- (id)defaultValueForHeader:(id)arg1;
- (void)deletePath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (void)enqueueBatchOfHTTPRequestOperations:(id)arg1 progressBlock:(id)arg2 completionBlock:(id)arg3;
- (void)enqueueBatchOfHTTPRequestOperationsWithRequests:(id)arg1 progressBlock:(id)arg2 completionBlock:(id)arg3;
- (void)enqueueHTTPRequestOperation:(id)arg1;
- (void)getPath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
- (id)init;
- (id)initWithBaseURL:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)multipartFormRequestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3 constructingBodyWithBlock:(id)arg4;
- (struct __SCNetworkReachability { }*)networkReachability;
- (int)networkReachabilityStatus;
- (id)networkReachabilityStatusBlock;
- (id)operationQueue;
- (int)parameterEncoding;
- (void)patchPath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
- (void)postPath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
- (void)putPath:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
- (bool)registerHTTPOperationClass:(Class)arg1;
- (id)registeredHTTPOperationClassNames;
- (id)requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3;
- (void)setAllowsInvalidSSLCertificate:(bool)arg1;
- (void)setAuthorizationHeaderWithToken:(id)arg1;
- (void)setAuthorizationHeaderWithUsername:(id)arg1 password:(id)arg2;
- (void)setBaseURL:(id)arg1;
- (void)setDefaultCredential:(id)arg1;
- (void)setDefaultHeader:(id)arg1 value:(id)arg2;
- (void)setDefaultHeaders:(id)arg1;
- (void)setDefaultSSLPinningMode:(int)arg1;
- (void)setNetworkReachability:(struct __SCNetworkReachability { }*)arg1;
- (void)setNetworkReachabilityStatus:(int)arg1;
- (void)setNetworkReachabilityStatusBlock:(id)arg1;
- (void)setOperationQueue:(id)arg1;
- (void)setParameterEncoding:(int)arg1;
- (void)setReachabilityStatusChangeBlock:(id)arg1;
- (void)setRegisteredHTTPOperationClassNames:(id)arg1;
- (void)setStringEncoding:(unsigned long long)arg1;
- (void)startMonitoringNetworkReachability;
- (void)stopMonitoringNetworkReachability;
- (unsigned long long)stringEncoding;
- (void)unregisterHTTPOperationClass:(Class)arg1;

@end
