/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface AFJSONRequestOperation : AFHTTPRequestOperation {
    NSError * _JSONError;
    unsigned long long  _JSONReadingOptions;
    id  _responseJSON;
}

@property (nonatomic, readwrite, retain) NSError *JSONError;
@property (nonatomic, readwrite) unsigned long long JSONReadingOptions;
@property (nonatomic, readwrite, retain) NSRecursiveLock *lock;
@property (nonatomic, readwrite, retain) id responseJSON;

+ (id)JSONRequestOperationWithRequest:(id)arg1 success:(id)arg2 failure:(id)arg3;
+ (id)acceptableContentTypes;
+ (bool)canProcessRequest:(id)arg1;

- (void).cxx_destruct;
- (id)JSONError;
- (unsigned long long)JSONReadingOptions;
- (id)error;
- (id)responseJSON;
- (void)setCompletionBlockWithSuccess:(id)arg1 failure:(id)arg2;
- (void)setJSONError:(id)arg1;
- (void)setJSONReadingOptions:(unsigned long long)arg1;
- (void)setResponseJSON:(id)arg1;

@end
