/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface AFMultipartBodyStream : NSInputStream <NSCopying, NSStreamDelegate> {
    NSEnumerator * _HTTPBodyPartEnumerator;
    NSMutableArray * _HTTPBodyParts;
    NSMutableData * _buffer;
    AFHTTPBodyPart * _currentHTTPBodyPart;
    double  _delay;
    NSInputStream * _inputStream;
    unsigned long long  _numberOfBytesInPacket;
    NSOutputStream * _outputStream;
    NSError * _streamError;
    unsigned long long  _streamStatus;
    unsigned long long  _stringEncoding;
}

@property (nonatomic, readwrite, retain) NSEnumerator *HTTPBodyPartEnumerator;
@property (nonatomic, readwrite, retain) NSMutableArray *HTTPBodyParts;
@property (nonatomic, readwrite, retain) NSMutableData *buffer;
@property (nonatomic, readonly) unsigned long long contentLength;
@property (nonatomic, readwrite, retain) AFHTTPBodyPart *currentHTTPBodyPart;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (nonatomic, readwrite) double delay;
@property (atomic, readonly, copy) NSString *description;
@property (getter=isEmpty, nonatomic, readonly) bool empty;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, retain) NSInputStream *inputStream;
@property (nonatomic, readwrite) unsigned long long numberOfBytesInPacket;
@property (nonatomic, readwrite, retain) NSOutputStream *outputStream;
@property (nonatomic, readwrite, retain) NSError *streamError;
@property (nonatomic, readwrite) unsigned long long streamStatus;
@property (nonatomic, readwrite) unsigned long long stringEncoding;
@property (atomic, readonly) Class superclass;

- (void).cxx_destruct;
- (id)HTTPBodyPartEnumerator;
- (id)HTTPBodyParts;
- (void)_scheduleInCFRunLoop:(struct __CFRunLoop { }*)arg1 forMode:(struct __CFString { }*)arg2;
- (bool)_setCFClientFlags:(unsigned long long)arg1 callback:(int (*)arg2 context:(struct { long long x1; void *x2; int (*x3)(); int (*x4)(); int (*x5)(); }*)arg3;
- (void)_unscheduleFromCFRunLoop:(struct __CFRunLoop { }*)arg1 forMode:(struct __CFString { }*)arg2;
- (void)appendHTTPBodyPart:(id)arg1;
- (id)buffer;
- (void)close;
- (unsigned long long)contentLength;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)currentHTTPBodyPart;
- (double)delay;
- (bool)getBuffer:(char **)arg1 length:(unsigned long long*)arg2;
- (bool)hasBytesAvailable;
- (id)initWithStringEncoding:(unsigned long long)arg1;
- (id)inputStream;
- (bool)isEmpty;
- (unsigned long long)numberOfBytesInPacket;
- (void)open;
- (id)outputStream;
- (id)propertyForKey:(id)arg1;
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;
- (void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2;
- (void)setBuffer:(id)arg1;
- (void)setCurrentHTTPBodyPart:(id)arg1;
- (void)setDelay:(double)arg1;
- (void)setHTTPBodyPartEnumerator:(id)arg1;
- (void)setHTTPBodyParts:(id)arg1;
- (void)setInitialAndFinalBoundaries;
- (void)setInputStream:(id)arg1;
- (void)setNumberOfBytesInPacket:(unsigned long long)arg1;
- (void)setOutputStream:(id)arg1;
- (bool)setProperty:(id)arg1 forKey:(id)arg2;
- (void)setStreamError:(id)arg1;
- (void)setStreamStatus:(unsigned long long)arg1;
- (void)setStringEncoding:(unsigned long long)arg1;
- (id)streamError;
- (unsigned long long)streamStatus;
- (unsigned long long)stringEncoding;

@end
