/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface AFNetworkActivityIndicatorManager : NSObject {
    long long  _activityCount;
    NSTimer * _activityIndicatorVisibilityTimer;
    bool  _enabled;
}

@property (nonatomic, readwrite) long long activityCount;
@property (nonatomic, readwrite, retain) NSTimer *activityIndicatorVisibilityTimer;
@property (getter=isEnabled, nonatomic, readwrite) bool enabled;
@property (nonatomic, readonly) bool isNetworkActivityIndicatorVisible;
@property (getter=isNetworkActivityIndicatorVisible, nonatomic, readonly) bool networkActivityIndicatorVisible;

+ (id)keyPathsForValuesAffectingIsNetworkActivityIndicatorVisible;
+ (id)sharedManager;

- (void).cxx_destruct;
- (long long)activityCount;
- (id)activityIndicatorVisibilityTimer;
- (void)dealloc;
- (void)decrementActivityCount;
- (void)incrementActivityCount;
- (id)init;
- (bool)isEnabled;
- (bool)isNetworkActivityIndicatorVisible;
- (void)networkingOperationDidFinish:(id)arg1;
- (void)networkingOperationDidStart:(id)arg1;
- (void)setActivityCount:(long long)arg1;
- (void)setActivityIndicatorVisibilityTimer:(id)arg1;
- (void)setEnabled:(bool)arg1;
- (void)updateNetworkActivityIndicatorVisibility;
- (void)updateNetworkActivityIndicatorVisibilityDelayed;

@end
