/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface AFQueryStringPair : NSObject {
    id  _field;
    id  _value;
}

@property (nonatomic, readwrite, retain) id field;
@property (nonatomic, readwrite, retain) id value;

- (void).cxx_destruct;
- (id)URLEncodedStringValueWithEncoding:(unsigned long long)arg1;
- (id)field;
- (id)initWithField:(id)arg1 value:(id)arg2;
- (void)setField:(id)arg1;
- (void)setValue:(id)arg1;
- (id)value;

@end
