/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface AFXMLRequestOperation : AFHTTPRequestOperation {
    NSError * _XMLError;
    NSXMLParser * _responseXMLParser;
}

@property (nonatomic, readwrite, retain) NSError *XMLError;
@property (nonatomic, readwrite, retain) NSXMLParser *responseXMLParser;

+ (id)XMLParserRequestOperationWithRequest:(id)arg1 success:(id)arg2 failure:(id)arg3;
+ (id)acceptableContentTypes;
+ (bool)canProcessRequest:(id)arg1;

- (void).cxx_destruct;
- (id)XMLError;
- (void)cancel;
- (id)error;
- (id)responseXMLParser;
- (void)setCompletionBlockWithSuccess:(id)arg1 failure:(id)arg2;
- (void)setResponseXMLParser:(id)arg1;
- (void)setXMLError:(id)arg1;

@end
