/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface RTBClass : NSObject {
    NSSet * _cachedMethodsNamePartsLowercase;
    bool  _shouldSortSubclasses;
    bool  _subclassesAreSorted;
    NSString * classObjectName;
    NSString * imagePath;
    NSMutableArray * subclassesStubs;
}

@property (nonatomic, readwrite, retain) NSSet *cachedMethodsNamePartsLowercase;
@property (nonatomic, readwrite, retain) NSString *classObjectName;
@property (nonatomic, readwrite, retain) NSString *imagePath;
@property (nonatomic, readwrite) bool shouldSortSubclasses;
@property (nonatomic, readwrite) bool subclassesAreSorted;
@property (nonatomic, readwrite, retain) NSMutableArray *subclassesStubs;

@end
