/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface RTBMethod : NSObject {
    NSArray * _cachedArgumentsTypesDecoded;
    NSDictionary * _cachedDyldInfoDictionary;
    NSNumber * _cachedHasArguments;
    bool  _isClassMethod;
    struct objc_method { } * _method;
}

@property (nonatomic, readwrite, retain) NSArray *cachedArgumentsTypesDecoded;
@property (nonatomic, readwrite, retain) NSDictionary *cachedDyldInfoDictionary;
@property (nonatomic, readwrite, retain) NSNumber *cachedHasArguments;
@property (nonatomic, readwrite) bool isClassMethod;
@property (nonatomic, readwrite) struct objc_method { }*method;

@end
