/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface RTBProtocol : NSObject {
    NSMutableSet * _conformingClassesStubsSet;
    NSString * _protocolName;
}

@property (nonatomic, readwrite, retain) NSMutableSet *conformingClassesStubsSet;
@property (nonatomic, readwrite, retain) NSString *protocolName;

@end
