/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface RTBRuntime : NSObject {
    NSMutableDictionary * _allClassStubsByImagePath;
    NSMutableDictionary * _allClassStubsByName;
    NSMutableDictionary * _allProtocolsByName;
    NSMutableArray * _rootClasses;
}

@property (nonatomic, readwrite, retain) NSMutableDictionary *allClassStubsByImagePath;
@property (nonatomic, readwrite, retain) NSMutableDictionary *allClassStubsByName;
@property (nonatomic, readwrite, retain) NSMutableDictionary *allProtocolsByName;
@property (nonatomic, readwrite, retain) NSMutableArray *rootClasses;

@end
