/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface RTBTypeDecoder : NSObject {
    NSMutableSet * _refdClasses;
    bool  _showCommentForBlocks;
    bool  currentWarning;
    const char * ivT;
    bool  methodWarning;
    NSMutableDictionary * namedStructs;
    bool  showFunctionSignatureNote;
    bool  showUnhandledWarning;
    int  structDepth;
    int  structPart;
}

@property (nonatomic, readwrite, retain) NSMutableDictionary *namedStructs;
@property (nonatomic, readwrite, retain) NSMutableSet *refdClasses;
@property (nonatomic, readwrite) bool showCommentForBlocks;

@end
