/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface SLItemTableView : UITableView <UITableViewDataSource, UITableViewDelegate> {
    id  _hightForHeaderHandler;
    NSMutableArray * _items;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _lastContentInset;
    struct CGPoint { 
        double x; 
        double y; 
    }  _lastContentOffset;
    UIControl * _lastControl;
    id  _target;
    id  _viewForHeaderHandler;
    id  _willDisplayCellHandler;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, copy) id hightForHeaderHandler;
@property (nonatomic, readwrite, retain) NSMutableArray *items;
@property (nonatomic, readwrite) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } lastContentInset;
@property (nonatomic, readwrite) struct CGPoint { double x1; double x2; } lastContentOffset;
@property (nonatomic, readwrite) UIControl *lastControl;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite) id target;
@property (nonatomic, readwrite, copy) id viewForHeaderHandler;
@property (nonatomic, readwrite, copy) id willDisplayCellHandler;

- (void).cxx_destruct;
- (void)addItem:(id)arg1;
- (void)addSection;
- (id)hightForHeaderHandler;
- (id)indexPathForItem:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)itemAtIndexPath:(id)arg1;
- (id)items;
- (void)keyboardWillHideAnimated:(bool)arg1;
- (void)keyboardWillShowWithContentOffset:(struct CGPoint { double x1; double x2; })arg1 contentInset:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg2 animated:(bool)arg3;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })lastContentInset;
- (struct CGPoint { double x1; double x2; })lastContentOffset;
- (id)lastControl;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)removeAllItems;
- (void)resignResponder;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setHightForHeaderHandler:(id)arg1;
- (void)setItems:(id)arg1;
- (void)setLastContentInset:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setLastContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)setLastControl:(id)arg1;
- (void)setTarget:(id)arg1;
- (void)setViewForHeaderHandler:(id)arg1;
- (void)setWillDisplayCellHandler:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableViewCell:(id)arg1 didCallActionSheetHandler:(id)arg2;
- (void)tableViewCell:(id)arg1 didCallButtonHandler:(id)arg2;
- (void)tableViewCell:(id)arg1 didCallSwitchHandler:(id)arg2;
- (void)tableViewCell:(id)arg1 didCallTextFieldHandler:(id)arg2;
- (id)target;
- (id)viewForHeaderHandler;
- (id)willDisplayCellHandler;

@end
