/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface SLItem : NSObject {
    NSMutableDictionary * _item;
}

@property (nonatomic, readwrite, retain) NSMutableDictionary *item;

- (void).cxx_destruct;
- (long long)accessoryType;
- (id)args;
- (id)attributedDetailText;
- (id)attributedText;
- (Class)cellClass;
- (double)cellHeight;
- (double)cellWidth;
- (id)description;
- (id)detailText;
- (id)image;
- (id)imageURL;
- (id)init;
- (id)item;
- (id)reuseIdentifier;
- (void)setAccessoryType:(long long)arg1;
- (void)setArgs:(id)arg1;
- (void)setAttributedDetailText:(id)arg1;
- (void)setAttributedText:(id)arg1;
- (void)setCellClass:(Class)arg1;
- (void)setCellHeight:(double)arg1;
- (void)setCellWidth:(double)arg1;
- (void)setDetailText:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setImageURL:(id)arg1;
- (void)setItem:(id)arg1;
- (void)setReuseIdentifier:(id)arg1;
- (void)setTag:(unsigned long long)arg1;
- (void)setText:(id)arg1;
- (void)setValue:(id)arg1;
- (unsigned long long)tag;
- (id)text;
- (id)value;

@end
