/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface SLItemTableViewCell : UITableViewCell {
    SLItemTableView * _delegate;
    SLItem * _item;
}

@property (nonatomic, readwrite) SLItemTableView *delegate;
@property (nonatomic, readwrite, retain) SLItem *item;

+ (double)cellHeightWithItem:(id)arg1 indexPath:(id)arg2;
+ (long long)defaultStyle;
+ (id)item;

- (void).cxx_destruct;
- (id)delegate;
- (id)description;
- (void)didSelectRowAtIndexPath:(id)arg1;
- (void)displayCellWithItem:(id)arg1;
- (id)initWithItem:(id)arg1 delegate:(id)arg2;
- (id)item;
- (void)layoutSubviews;
- (void)setAccessoryType:(long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setItem:(id)arg1;
- (void)setupCell;

@end
