/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface SLItemImageCell : SLItemTableViewCell

- (void)displayCellWithItem:(id)arg1;
- (void)layoutSubviews;

@end
