/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UAUniqloView : UIView <UIWebViewDelegate> {
    UIView * _backgroundView;
    UIActivityIndicatorView * _indicatorView;
    UIWebView * _webView;
}

@property (nonatomic, readwrite, retain) UIView *backgroundView;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, retain) UIActivityIndicatorView *indicatorView;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UIWebView *webView;

+ (id)makeCloseButtonWithColor:(id)arg1;

- (void).cxx_destruct;
- (id)backgroundView;
- (void)dealloc;
- (void)dismiss;
- (id)indicatorView;
- (void)setBackgroundView:(id)arg1;
- (void)setIndicatorView:(id)arg1;
- (void)setWebView:(id)arg1;
- (void)setup;
- (void)showInView:(id)arg1 completion:(id)arg2;
- (id)webView;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;

@end
