/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWActionSheet : UIView {
    NSArray * _buttons;
    id  _context;
    id  _delegate;
    unsigned long long  _selectedIndex;
    UIView * _sheetView;
    UILabel * _titleLabel;
    UIView * _transitionView;
}

@property (nonatomic, readwrite, retain) id context;
@property (nonatomic, readwrite) id delegate;

+ (id)actionSheetWithDelegate:(id)arg1 title:(id)arg2 buttons:(id)arg3 attributes:(id)arg4;

- (void).cxx_destruct;
- (void)buttonDidTouch:(id)arg1;
- (void)colorDidUpdate:(id)arg1;
- (id)context;
- (id)delegate;
- (void)dismiss;
- (id)initWithDelegate:(id)arg1 title:(id)arg2 buttons:(id)arg3 attributes:(id)arg4;
- (unsigned long long)selectedIndex;
- (void)setContext:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)showInView:(id)arg1;
- (void)willMoveToWindow:(id)arg1;

@end
