/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWAlarmManager : NSObject {
    NSTimer * _clockTimer;
    int  _hour;
    int  _minute;
    int  _week;
}

@property (getter=alarmList, setter=setAlarmList:, nonatomic, readwrite, retain) NSArray *alarmList;
@property (nonatomic, readwrite) NSTimer *clockTimer;
@property (nonatomic, readwrite) int hour;
@property (nonatomic, readwrite) int minute;
@property (nonatomic, readwrite, retain) NSDictionary *reservedAlarm;
@property (nonatomic, readwrite) int week;

+ (void)localizedTimeWithHour:(int)arg1 minute:(int)arg2 hour:(int*)arg3 ampm:(int*)arg4;
+ (id)sharedManager;

- (void).cxx_destruct;
- (void)addAlarm:(id)arg1;
- (id)alarmList;
- (id)clockTimer;
- (int)hour;
- (id)init;
- (int)minute;
- (void)removeAlarmAtIndex:(unsigned long long)arg1;
- (void)replaceAlarm:(id)arg1 atIndex:(int)arg2;
- (id)reservedAlarm;
- (void)setAlarmList:(id)arg1;
- (void)setClockTimer:(id)arg1;
- (void)setHour:(int)arg1;
- (void)setMinute:(int)arg1;
- (void)setReservedAlarm:(id)arg1;
- (void)setWeek:(int)arg1;
- (id)sortedAlarmList:(id)arg1;
- (void)timerExpired:(id)arg1;
- (int)week;

@end
