/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWAlarmListViewController : UWCommonViewController <UITableViewDataSource, UITableViewDelegate> {
    UWImageButton * _editButton;
    UITableView * _tableView;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (nonatomic, readwrite, retain) UWImageButton *editButton;
@property (atomic, readonly) unsigned long long hash;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UITableView *tableView;

- (void).cxx_destruct;
- (void)addButtonHandller:(id)arg1;
- (void)closeButtonHandller:(id)arg1;
- (void)doneButtonHandller:(id)arg1;
- (void)editAlarmWithIndex:(int)arg1;
- (void)editAlarmWithIndex:(int)arg1 animated:(bool)arg2;
- (id)editButton;
- (void)editButtonHandller:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setEditButton:(id)arg1;
- (void)setTableView:(id)arg1;
- (void)startWaitingAlarmWithIndex:(int)arg1;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateButton;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
