/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWAlarmEditViewController : UWCommonViewController <UITableViewDataSource, UITableViewDelegate> {
    int  _alarmIndex;
    NSMutableDictionary * _alarmSetting;
    UWPickerView * _pickerView;
    UWSwitch * _switchView;
    UITableView * _tableView;
}

@property (nonatomic, readwrite) int alarmIndex;
@property (nonatomic, readwrite, retain) NSMutableDictionary *alarmSetting;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, retain) UWPickerView *pickerView;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UWSwitch *switchView;
@property (nonatomic, readwrite, retain) UITableView *tableView;

- (void).cxx_destruct;
- (int)alarmIndex;
- (id)alarmSetting;
- (void)backButtonHandller:(id)arg1;
- (void)closeButtonHandller:(id)arg1;
- (id)editedSetting;
- (id)init;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)pickerView;
- (void)setAlarmIndex:(int)arg1;
- (void)setAlarmSetting:(id)arg1;
- (void)setButtonHandller:(id)arg1;
- (void)setPickerView:(id)arg1;
- (void)setSwitchView:(id)arg1;
- (void)setTableView:(id)arg1;
- (void)startWattingAlarm;
- (id)switchView;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

@end
