/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWClockAlarmViewController : UWClockCommonViewController <UIAlertViewDelegate> {
    NSDictionary * _alarm;
    UIView * _contentView;
    UIView * _noticeView;
    NSDictionary * _postInfo;
    bool  _showsNotice;
    NSDate * _snoozeDate;
    int  _state;
}

@property (nonatomic, readwrite, copy) NSDictionary *alarm;
@property (nonatomic, readwrite, retain) UIView *contentView;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, retain) UIView *noticeView;
@property (nonatomic, readwrite, retain) NSDictionary *postInfo;
@property (nonatomic, readwrite) bool showsNotice;
@property (nonatomic, readwrite, retain) NSDate *snoozeDate;
@property (nonatomic, readwrite) int state;
@property (atomic, readonly) Class superclass;

- (void).cxx_destruct;
- (id)alarm;
- (void)alarmDidRaise:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)cancelButtonHandler:(id)arg1;
- (void)colorDidUpdate:(id)arg1;
- (id)contentView;
- (bool)isEnoughSleepTime;
- (id)noticeView;
- (void)okButtonHandler:(id)arg1;
- (id)postInfo;
- (void)postWithMessage:(id)arg1;
- (bool)saveSleepTime;
- (void)setAlarm:(id)arg1;
- (void)setContentView:(id)arg1;
- (void)setNoticeView:(id)arg1;
- (void)setPostInfo:(id)arg1;
- (void)setShowsNotice:(bool)arg1;
- (void)setSnoozeDate:(id)arg1;
- (void)setState:(int)arg1;
- (void)shareButtonHandler:(id)arg1;
- (void)showAuth;
- (void)showShareIfNeeded;
- (bool)showsNotice;
- (double)sleepTime;
- (void)snoozeButtonHandler:(id)arg1;
- (id)snoozeDate;
- (void)startAlarm;
- (int)state;
- (void)stopAlarm;
- (void)stopButtonHandler:(id)arg1;
- (void)timeDidUpdate:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;
- (void)wakeupButtonHandler:(id)arg1;

@end
