/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWDropLayer : CALayer {
    int  _count;
}

@property (nonatomic, readwrite) int count;

- (int)count;
- (void)drawInContext:(struct CGContext { }*)arg1;
- (id)initWithCount:(int)arg1;
- (void)setCount:(int)arg1;

@end
