/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWGPSManager : NSObject <CLLocationManagerDelegate> {
    bool  _isUpdatingLocation;
    CLLocation * _latestLocation;
    CLLocationManager * _locationManager;
    id  _response;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite) bool isUpdatingLocation;
@property (nonatomic, readwrite, retain) CLLocation *latestLocation;
@property (nonatomic, readwrite, retain) CLLocationManager *locationManager;
@property (nonatomic, readwrite, copy) id response;
@property (atomic, readonly) Class superclass;

- (void).cxx_destruct;
- (void)cancelUpdatingLocation;
- (void)dealloc;
- (bool)isUpdatingLocation;
- (id)latestLocation;
- (id)locationManager;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (id)response;
- (void)setIsUpdatingLocation:(bool)arg1;
- (void)setLatestLocation:(id)arg1;
- (void)setLocationManager:(id)arg1;
- (void)setResponse:(id)arg1;
- (void)startUpdatingLocation;

@end
