/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWHowToUseViewController : UWCommonViewController

- (void)backButtonHandler:(id)arg1;
- (void)viewDidLoad;

@end
