/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWHowToUseView : UIView <UIScrollViewDelegate> {
    UWPageControl * _pageControl;
    UIScrollView * _scrollView;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, retain) UWPageControl *pageControl;
@property (nonatomic, readwrite, retain) UIScrollView *scrollView;
@property (atomic, readonly) Class superclass;

- (void).cxx_destruct;
- (void)colorDidUpdate:(id)arg1;
- (void)dismiss;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)pageControl;
- (void)pageControlDidTouch:(id)arg1;
- (id)scrollView;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setPageControl:(id)arg1;
- (void)setScrollView:(id)arg1;
- (void)showInView:(id)arg1;
- (void)willMoveToWindow:(id)arg1;

@end
