/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWImageButton : UIImageView {
    SEL  _action;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _customAlignmentRectInsets;
    id  _delegate;
    bool  _isOver;
    bool  _isToggleSwitch;
    bool  _isTouchEnded;
    bool  _lastSelected;
    UIImage * _normalImage;
    UIView * _overlay;
    bool  _selected;
    UIImage * _selectedImage;
    id  _target;
    UILabel * _titleLabel;
    double  _touchAlpha;
    int  _touchStyle;
}

@property (nonatomic, readwrite) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } customAlignmentRectInsets;
@property (nonatomic, readwrite) id delegate;
@property (nonatomic, readwrite) bool isToggleSwitch;
@property (nonatomic, readonly) bool isTouchEnded;
@property (nonatomic, readonly) UIView *overlay;
@property (nonatomic, readwrite) bool selected;
@property (getter=title, setter=setTitle:, nonatomic, readwrite, retain) NSString *title;
@property (nonatomic, readonly) UILabel *titleLabel;
@property (nonatomic, readwrite) double touchAlpha;
@property (nonatomic, readwrite) int touchStyle;

+ (id)buttonWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;

- (void).cxx_destruct;
- (void)_postAction;
- (void)_updateViewWithTouched:(bool)arg1;
- (void)addTarget:(id)arg1 action:(SEL)arg2;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })alignmentRectInsets;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })customAlignmentRectInsets;
- (id)delegate;
- (bool)hitTest:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isToggleSwitch;
- (bool)isTouchEnded;
- (id)overlay;
- (bool)selected;
- (void)setCustomAlignmentRectInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setDelegate:(id)arg1;
- (void)setImageWithName:(id)arg1;
- (void)setImageWithName:(id)arg1 selectedImageWithName:(id)arg2;
- (void)setImageWithName:(id)arg1 selectedImageWithName:(id)arg2 stretched:(bool)arg3;
- (void)setImageWithName:(id)arg1 stretched:(bool)arg2;
- (void)setIsToggleSwitch:(bool)arg1;
- (void)setSelected:(bool)arg1;
- (void)setTitle:(id)arg1;
- (void)setTouchAlpha:(double)arg1;
- (void)setTouchStyle:(int)arg1;
- (id)title;
- (id)titleLabel;
- (double)touchAlpha;
- (int)touchStyle;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

@end
