/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWIntroViewController : UWCommonViewController {
    bool  _shouldBackToInformation;
}

@property (nonatomic, readwrite) bool shouldBackToInformation;

- (void)backButtonHandler:(id)arg1;
- (void)gotoHome;
- (void)gotoSetting;
- (void)nextButtonHandller:(id)arg1;
- (void)requestInit;
- (void)setShouldBackToInformation:(bool)arg1;
- (bool)shouldBackToInformation;
- (void)viewDidLoad;

@end
