/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWInfoViewController : UWCommonViewController <UITableViewDataSource, UITableViewDelegate> {
    NSArray * _rowTitles;
    UITableView * _tableView;
}

@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, retain) NSArray *rowTitles;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UITableView *tableView;

- (void).cxx_destruct;
- (void)doneButtonHandller:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)rowTitles;
- (void)setRowTitles:(id)arg1;
- (void)setTableView:(id)arg1;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
