/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWLocationTopViewController : UWCommonViewController <UITableViewDataSource, UITableViewDelegate> {
    UWGPSManager * _GPSManager;
    UWSettingsViewController * _settingsViewController;
    UITableView * _tableView;
    NSDictionary * _tempLocation;
}

@property (nonatomic, readwrite, retain) UWGPSManager *GPSManager;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite) UWSettingsViewController *settingsViewController;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UITableView *tableView;
@property (nonatomic, readwrite, copy) NSDictionary *tempLocation;

- (void).cxx_destruct;
- (id)GPSManager;
- (void)cancelButtonHandller:(id)arg1;
- (void)cancelUpdatingLocation;
- (void)locationDidUpdateWithLocation:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)saveButtonHandller:(id)arg1;
- (void)setGPSManager:(id)arg1;
- (void)setSettingsViewController:(id)arg1;
- (void)setTableView:(id)arg1;
- (void)setTempLocation:(id)arg1;
- (id)settingsViewController;
- (void)startUpdatingLocation;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tempLocation;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
