/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWLogGraphCell : UICollectionViewCell {
    double  _amount;
    double  _hourDistance;
    bool  _isCurrent;
    NSString * _label;
    int  _mode;
}

@property (nonatomic, readwrite) double amount;
@property (nonatomic, readwrite) double hourDistance;
@property (nonatomic, readwrite) bool isCurrent;
@property (nonatomic, readwrite, retain) NSString *label;
@property (nonatomic, readwrite) int mode;

- (void).cxx_destruct;
- (double)amount;
- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (double)hourDistance;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isCurrent;
- (id)label;
- (int)mode;
- (void)setAmount:(double)arg1;
- (void)setHourDistance:(double)arg1;
- (void)setIsCurrent:(bool)arg1;
- (void)setLabel:(id)arg1;
- (void)setMode:(int)arg1;

@end
