/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWLogSleepTimeLabel : UIView {
    int  _day;
    int  _hour;
    int  _minute;
    int  _month;
    int  _year;
}

@property (nonatomic, readwrite) int day;
@property (nonatomic, readwrite) int hour;
@property (nonatomic, readwrite) int minute;
@property (nonatomic, readwrite) int month;
@property (nonatomic, readwrite) int year;

- (int)day;
- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (int)hour;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (int)minute;
- (int)month;
- (void)setDay:(int)arg1;
- (void)setHour:(int)arg1;
- (void)setMinute:(int)arg1;
- (void)setMonth:(int)arg1;
- (void)setYear:(int)arg1;
- (int)year;

@end
