/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWLogGraphView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, UIScrollViewDelegate> {
    NSMutableArray * _cachedLogs;
    UICollectionView * _collectionView;
    long long  _currentYear;
    double  _hourDistance;
    UICollectionViewFlowLayout * _layout;
    int  _mode;
    UILabel * _yearLabel;
}

@property (nonatomic, readwrite, retain) NSMutableArray *cachedLogs;
@property (nonatomic, readwrite, retain) UICollectionView *collectionView;
@property (nonatomic, readwrite) long long currentYear;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite) double hourDistance;
@property (nonatomic, readwrite, retain) UICollectionViewFlowLayout *layout;
@property (nonatomic, readwrite) int mode;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UILabel *yearLabel;

- (void).cxx_destruct;
- (id)cachedLogs;
- (id)collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)currentYear;
- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (double)hourDistance;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)layout;
- (id)logsAtPage:(long long)arg1;
- (int)mode;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)setCachedLogs:(id)arg1;
- (void)setCollectionView:(id)arg1;
- (void)setCurrentYear:(long long)arg1;
- (void)setHourDistance:(double)arg1;
- (void)setLayout:(id)arg1;
- (void)setMode:(int)arg1;
- (void)setYearLabel:(id)arg1;
- (id)yearLabel;

@end
