/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWLocationListViewController : UWCommonViewController <UITableViewDataSource, UITableViewDelegate> {
    NSDictionary * _citydata;
    NSString * _country;
    NSIndexPath * _hilightIndexPath;
    NSIndexPath * _loadingIndexPath;
    NSArray * _rowTitles;
    NSArray * _sectionHeaderTitles;
    bool  _shouldHighlightCell;
    NSString * _state;
    UITableView * _tableView;
    UWLocationTopViewController * _topLocationViewController;
}

@property (nonatomic, readwrite, retain) NSDictionary *citydata;
@property (nonatomic, readwrite, retain) NSString *country;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, retain) NSIndexPath *hilightIndexPath;
@property (nonatomic, readwrite, retain) NSIndexPath *loadingIndexPath;
@property (nonatomic, readwrite, retain) NSArray *rowTitles;
@property (nonatomic, readwrite, retain) NSArray *sectionHeaderTitles;
@property (nonatomic, readwrite) bool shouldHighlightCell;
@property (nonatomic, readwrite, retain) NSString *state;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UITableView *tableView;
@property (nonatomic, readwrite) UWLocationTopViewController *topLocationViewController;

- (void).cxx_destruct;
- (id)JSONWithName:(id)arg1;
- (void)backButtonHandller:(id)arg1;
- (id)citydata;
- (void)colorDidUpdate:(id)arg1;
- (id)country;
- (id)hilightIndexPath;
- (id)loadingIndexPath;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)requestLocation;
- (id)rowTitles;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (id)sectionHeaderTitles;
- (void)setCitydata:(id)arg1;
- (void)setCountry:(id)arg1;
- (void)setHilightIndexPath:(id)arg1;
- (void)setLoadingIndexPath:(id)arg1;
- (void)setRowTitles:(id)arg1;
- (void)setSectionHeaderTitles:(id)arg1;
- (void)setShouldHighlightCell:(bool)arg1;
- (void)setState:(id)arg1;
- (void)setTableView:(id)arg1;
- (void)setTopLocationViewController:(id)arg1;
- (bool)shouldHighlightCell;
- (id)state;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)topLocationViewController;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;

@end
