/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWPickerView : UIPickerView <UIPickerViewDataSource, UIPickerViewDelegate> {
    bool  _layoutFinished;
    int  _minuteResolution;
}

@property (getter=currentHour, setter=setCurrentHour:, nonatomic, readwrite) int currentHour;
@property (getter=currentMinute, setter=setCurrentMinute:, nonatomic, readwrite) int currentMinute;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite) int minuteResolution;
@property (atomic, readonly) Class superclass;

- (int)currentHour;
- (int)currentMinute;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (int)minuteResolution;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (double)pickerView:(id)arg1 widthForComponent:(long long)arg2;
- (void)setCurrentHour:(int)arg1;
- (void)setCurrentMinute:(int)arg1;
- (void)setMinuteResolution:(int)arg1;

@end
