/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWRootViewController : UWCommonViewController {
    UIColor * _color;
    UIImage * _coloredImage;
    int  _selectedIndex;
    UIViewController * _selectedViewController;
    UWTabButtonView * _tabButtonView;
}

@property (nonatomic, readwrite, retain) UIColor *color;
@property (nonatomic, readwrite, retain) UIImage *coloredImage;
@property (nonatomic, readwrite) int selectedIndex;
@property (nonatomic, readwrite, retain) UIViewController *selectedViewController;
@property (nonatomic, readwrite, retain) UWTabButtonView *tabButtonView;

+ (id)sharedController;

- (void).cxx_destruct;
- (id)color;
- (id)colorWithWeek:(int)arg1;
- (id)coloredImage;
- (id)makeColorImageWithColor:(id)arg1;
- (int)selectedIndex;
- (id)selectedViewController;
- (void)setColor:(id)arg1;
- (void)setColoredImage:(id)arg1;
- (void)setSelectedIndex:(int)arg1;
- (void)setSelectedViewController:(id)arg1;
- (void)setTabButtonView:(id)arg1;
- (void)tabButtonDidSelect:(id)arg1;
- (id)tabButtonView;
- (void)updateColor;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;

@end
