/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWSettingsViewController : UWCommonViewController <UITableViewDataSource, UITableViewDelegate> {
    UWGPSManager * _GPSManager;
    bool  _autoSearchLocationEnabled;
    bool  _autosave;
    bool  _isFirstLaunching;
    NSArray * _sectionHeaderTitles;
    NSMutableArray * _segmentedButtonIndices;
    NSArray * _segmentedButtonTitles;
    UITableView * _tableView;
    NSDictionary * _tempLocation;
    int  _tempSNSType;
    int  _tempTemperatureUnit;
    int  _tempVocalType;
}

@property (nonatomic, readwrite, retain) UWGPSManager *GPSManager;
@property (nonatomic, readwrite) bool autoSearchLocationEnabled;
@property (nonatomic, readwrite) bool autosave;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite) bool isFirstLaunching;
@property (nonatomic, readwrite, retain) NSArray *sectionHeaderTitles;
@property (nonatomic, readwrite, retain) NSMutableArray *segmentedButtonIndices;
@property (nonatomic, readwrite, retain) NSArray *segmentedButtonTitles;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UITableView *tableView;
@property (nonatomic, readwrite, retain) NSDictionary *tempLocation;
@property (nonatomic, readwrite) int tempSNSType;
@property (nonatomic, readwrite) int tempTemperatureUnit;
@property (nonatomic, readwrite) int tempVocalType;

- (void).cxx_destruct;
- (id)GPSManager;
- (void)actionSheetWillDismiss:(id)arg1;
- (void)authViewControllerAuthFaild:(id)arg1;
- (void)authViewControllerAuthSucceed:(id)arg1;
- (bool)autoSearchLocationEnabled;
- (bool)autosave;
- (void)cancelButtonHandller:(id)arg1;
- (void)cancelUpdatingLocation;
- (void)colorDidUpdate:(id)arg1;
- (bool)isFirstLaunching;
- (void)locationDidUpdateWithLocation:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)requestWeatherAPI;
- (void)saveButtonHandller:(id)arg1;
- (void)saveTempValuesToUserDefaults;
- (id)sectionHeaderTitles;
- (void)segmentedButtonDidTouch:(id)arg1;
- (id)segmentedButtonIndices;
- (id)segmentedButtonTitles;
- (void)setAutoSearchLocationEnabled:(bool)arg1;
- (void)setAutosave:(bool)arg1;
- (void)setGPSManager:(id)arg1;
- (void)setIsFirstLaunching:(bool)arg1;
- (void)setSectionHeaderTitles:(id)arg1;
- (void)setSegmentedButtonIndices:(id)arg1;
- (void)setSegmentedButtonTitles:(id)arg1;
- (void)setTableView:(id)arg1;
- (void)setTempLocation:(id)arg1;
- (void)setTempSNSType:(int)arg1;
- (void)setTempTemperatureUnit:(int)arg1;
- (void)setTempVocalType:(int)arg1;
- (void)startUpdatingLocation;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tempLocation;
- (int)tempSNSType;
- (int)tempTemperatureUnit;
- (int)tempVocalType;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
