/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWShareFacebookView : UIView <UITextViewDelegate> {
    UWClockAlarmViewController * _alarmViewController;
    UIView * _barView;
    UIImageView * _checkOffView;
    UIView * _checkOnView;
    UIButton * _finishEditingButton;
    NSString * _message;
    UIView * _outlineView;
    NSDictionary * _postInfo;
    UIView * _shareButtonView;
    UITextView * _textView;
}

@property (nonatomic, readwrite) UWClockAlarmViewController *alarmViewController;
@property (nonatomic, readwrite, retain) UIView *barView;
@property (nonatomic, readwrite, retain) UIImageView *checkOffView;
@property (nonatomic, readwrite, retain) UIView *checkOnView;
@property (atomic, readonly, copy) NSString *debugDescription;
@property (atomic, readonly, copy) NSString *description;
@property (nonatomic, readwrite, retain) UIButton *finishEditingButton;
@property (atomic, readonly) unsigned long long hash;
@property (nonatomic, readwrite, retain) NSString *message;
@property (nonatomic, readwrite, retain) UIView *outlineView;
@property (nonatomic, readwrite, retain) NSDictionary *postInfo;
@property (nonatomic, readwrite, retain) UIView *shareButtonView;
@property (atomic, readonly) Class superclass;
@property (nonatomic, readwrite, retain) UITextView *textView;

- (void).cxx_destruct;
- (id)alarmViewController;
- (id)barView;
- (void)cancelButtonHandler:(id)arg1;
- (void)checkButtonHandler:(id)arg1;
- (id)checkOffView;
- (id)checkOnView;
- (bool)checked;
- (void)colorDidUpdate:(id)arg1;
- (void)dismiss;
- (id)finishEditingButton;
- (void)finishEditingHandler:(id)arg1;
- (id)makeMessage;
- (id)message;
- (id)outlineView;
- (id)postInfo;
- (void)setAlarmViewController:(id)arg1;
- (void)setBarView:(id)arg1;
- (void)setCheckOffView:(id)arg1;
- (void)setCheckOnView:(id)arg1;
- (void)setChecked:(bool)arg1;
- (void)setFinishEditingButton:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setOutlineView:(id)arg1;
- (void)setPostInfo:(id)arg1;
- (void)setShareButtonView:(id)arg1;
- (void)setTextView:(id)arg1;
- (void)shareButtonHandler:(id)arg1;
- (id)shareButtonView;
- (void)showInView:(id)arg1;
- (id)textView;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)willMoveToWindow:(id)arg1;

@end
