/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWSnowLayer : CALayer {
    double  _dy;
    int  _fadeoutState;
    bool  _isActive;
    double  _life;
    double  _x;
    double  _y;
}

@property (nonatomic, readwrite) double dy;
@property (nonatomic, readwrite) int fadeoutState;
@property (nonatomic, readwrite) bool isActive;
@property (nonatomic, readwrite) double life;
@property (nonatomic, readwrite) double x;
@property (nonatomic, readwrite) double y;

- (bool)birth;
- (double)dy;
- (int)fadeoutState;
- (bool)isActive;
- (double)life;
- (void)setDy:(double)arg1;
- (void)setFadeoutState:(int)arg1;
- (void)setIsActive:(bool)arg1;
- (void)setLife:(double)arg1;
- (void)setX:(double)arg1;
- (void)setY:(double)arg1;
- (void)update:(float)arg1;
- (double)x;
- (double)y;

@end
