/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWSwitch : UIView {
    SEL  _action;
    UIImageView * _bodyView;
    bool  _on;
    UIView * _overlayView;
    bool  _previousOn;
    UIImageView * _shadowView;
    bool  _swipeFlag;
    id  _target;
    double  _translation;
}

@property (nonatomic, readwrite) bool on;

+ (id)defaultSwitch;

- (void).cxx_destruct;
- (void)addTarget:(id)arg1 action:(SEL)arg2;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)on;
- (void)setBodyImage:(id)arg1 stretched:(bool)arg2;
- (void)setBodySize:(struct CGSize { double x1; double x2; })arg1;
- (void)setCornerRadius:(double)arg1;
- (void)setOn:(bool)arg1;
- (void)setOn:(bool)arg1 animated:(bool)arg2;
- (void)setOverlaySize:(struct CGSize { double x1; double x2; })arg1 cornerRadius:(double)arg2;
- (void)setShadowImage:(id)arg1 stretched:(bool)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

@end
