/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWTableViewCell : UITableViewCell {
    int  _customAccessoryType;
    int  _customEditingAccessoryType;
    UWImageButton * _deleteButton;
    UWImageButton * _editControlButton;
    bool  _editingEnabled;
}

- (void).cxx_destruct;
- (id)accessoryAsButton;
- (id)accessoryAsIndicator;
- (id)accessoryAsSwitch;
- (int)customAccessoryType;
- (id)customAccessoryViewWithType:(int)arg1;
- (int)customEditingAccessoryType;
- (id)deleteButton;
- (void)deleteButtonHandler:(id)arg1;
- (id)editControlButton;
- (void)editControlButtonHandler:(id)arg1;
- (id)editingAccessoryAsButton;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)setCustomAccessoryType:(int)arg1;
- (void)setCustomEditingAccessoryType:(int)arg1;
- (void)setEditingState:(unsigned long long)arg1;
- (id)tableView;
- (void)willTransitionToState:(unsigned long long)arg1;

@end
