/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWTemperatureLabel : UILabel {
    int  _high;
    int  _low;
}

@property (nonatomic, readwrite) int high;
@property (nonatomic, readwrite) int low;

- (int)high;
- (id)init;
- (int)low;
- (void)setHigh:(int)arg1;
- (void)setHigh:(int)arg1 low:(int)arg2;
- (void)setLow:(int)arg1;

@end
