/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWTemplateImageLayer : CALayer {
    UIImage * _image;
    UIColor * _tintColor;
}

@property (nonatomic, readwrite, retain) UIImage *image;
@property (nonatomic, readwrite, retain) UIColor *tintColor;

- (void).cxx_destruct;
- (void)drawInContext:(struct CGContext { }*)arg1;
- (id)image;
- (id)initWithImage:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setTintColor:(id)arg1;
- (id)tintColor;

@end
