/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWTimeLabel : UIView {
    int  _hour;
    int  _minute;
}

@property (nonatomic, readwrite) int hour;
@property (nonatomic, readwrite) int minute;

- (void)drawAtPoint:(struct CGPoint { double x1; double x2; })arg1 number:(int)arg2 attributes:(id)arg3;
- (void)drawRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (int)hour;
- (id)init;
- (int)minute;
- (void)setHour:(int)arg1;
- (void)setHour:(int)arg1 minute:(int)arg2;
- (void)setMinute:(int)arg1;

@end
