/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWWeatherFoggyView : UWWeatherView {
    NSMutableArray * _particles;
}

@property (nonatomic, readwrite, retain) NSMutableArray *particles;

- (void).cxx_destruct;
- (void)drawWave;
- (id)particles;
- (void)setParticles:(id)arg1;
- (void)setup;
- (void)start;
- (void)stop;
- (void)update:(id)arg1;

@end
