/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWWeatherUnknownView : UWWeatherView {
    CALayer * _questionLayer;
}

@property (nonatomic, readwrite, retain) CALayer *questionLayer;

- (void).cxx_destruct;
- (id)questionLayer;
- (void)setQuestionLayer:(id)arg1;
- (void)setup;
- (void)start;
- (void)update:(id)arg1;

@end
