/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWWeatherStormyView : UWWeatherView {
    int  _counter;
    NSMutableArray * _dropLayers;
    CALayer * _thunderLayer;
}

@property (nonatomic, readwrite) int counter;
@property (nonatomic, readwrite, retain) NSMutableArray *dropLayers;
@property (nonatomic, readwrite, retain) CALayer *thunderLayer;

- (void).cxx_destruct;
- (int)counter;
- (id)dropLayers;
- (void)setCounter:(int)arg1;
- (void)setDropLayers:(id)arg1;
- (void)setThunderLayer:(id)arg1;
- (void)setup;
- (void)start;
- (void)stop;
- (id)thunderLayer;
- (void)update:(id)arg1;

@end
