/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWWeatherSnowyView : UWWeatherView {
    NSMutableArray * _particles;
    double  _timeInterval;
}

@property (nonatomic, readwrite, retain) NSMutableArray *particles;
@property (nonatomic, readwrite) double timeInterval;

- (void).cxx_destruct;
- (void)generateSnow;
- (id)particles;
- (void)setParticles:(id)arg1;
- (void)setTimeInterval:(double)arg1;
- (void)setup;
- (void)start;
- (void)stop;
- (double)timeInterval;
- (void)update:(id)arg1;

@end
