/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWWeatherRainyView : UWWeatherView {
    NSMutableArray * _dropLayers;
}

@property (nonatomic, readwrite, retain) NSMutableArray *dropLayers;

- (void).cxx_destruct;
- (id)dropLayers;
- (void)setDropLayers:(id)arg1;
- (void)setup;
- (void)start;
- (void)stop;
- (void)update:(id)arg1;

@end
