/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWWeatherSunnyView : UWWeatherView {
    CALayer * _barNode;
    NSMutableArray * _bars;
}

@property (nonatomic, readwrite, retain) CALayer *barNode;
@property (nonatomic, readwrite, retain) NSMutableArray *bars;

- (void).cxx_destruct;
- (id)barNode;
- (id)bars;
- (void)setBarNode:(id)arg1;
- (void)setBars:(id)arg1;
- (void)setup;
- (void)start;
- (void)stop;
- (void)update:(id)arg1;

@end
