/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWWeatherView : UIView {
    CADisplayLink * _displayLink;
    NSDate * _lastDate;
}

@property (nonatomic, readwrite, retain) CADisplayLink *displayLink;
@property (nonatomic, readwrite, retain) NSDate *lastDate;

- (void).cxx_destruct;
- (void)colorDidUpdate:(id)arg1;
- (id)displayLink;
- (id)init;
- (bool)isAnimating;
- (id)lastDate;
- (void)remove;
- (void)setDisplayLink:(id)arg1;
- (void)setLastDate:(id)arg1;
- (void)setup;
- (void)start;
- (void)startTimerWithInterval:(double)arg1;
- (void)stop;
- (void)update:(id)arg1;

@end
