/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/UniqloWakeUp
 */

@interface UWWeatherCloudyView : UWWeatherView {
    CALayer * _cloudLayer;
}

@property (nonatomic, readwrite, retain) CALayer *cloudLayer;

- (void).cxx_destruct;
- (id)cloudLayer;
- (void)setCloudLayer:(id)arg1;
- (void)setup;
- (void)start;
- (void)stop;
- (void)update:(id)arg1;

@end
