/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface YYClassIvarInfo : NSObject {
    struct objc_ivar { } * _ivar;
    NSString * _name;
    long long  _offset;
    unsigned long long  _type;
    NSString * _typeEncoding;
}

@property (nonatomic, readonly) struct objc_ivar { }*ivar;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) long long offset;
@property (nonatomic, readonly) unsigned long long type;
@property (nonatomic, readonly) NSString *typeEncoding;

@end
