/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface YYClassInfo : NSObject {
    Class  _cls;
    bool  _isMeta;
    NSDictionary * _ivarInfos;
    Class  _metaCls;
    NSDictionary * _methodInfos;
    NSString * _name;
    bool  _needUpdate;
    NSDictionary * _propertyInfos;
    YYClassInfo * _superClassInfo;
    Class  _superCls;
}

@property (nonatomic, readonly) Class cls;
@property (nonatomic, readonly) bool isMeta;
@property (nonatomic, readonly) NSDictionary *ivarInfos;
@property (nonatomic, readonly) Class metaCls;
@property (nonatomic, readonly) NSDictionary *methodInfos;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) NSDictionary *propertyInfos;
@property (nonatomic, readonly) YYClassInfo *superClassInfo;
@property (nonatomic, readonly) Class superCls;

@end
