/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface YYClassPropertyInfo : NSObject {
    Class  _cls;
    SEL  _getter;
    NSString * _ivarName;
    NSString * _name;
    struct objc_property { } * _property;
    NSArray * _protocols;
    SEL  _setter;
    unsigned long long  _type;
    NSString * _typeEncoding;
}

@property (nonatomic, readonly) Class cls;
@property (nonatomic, readonly) SEL getter;
@property (nonatomic, readonly) NSString *ivarName;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) struct objc_property { }*property;
@property (nonatomic, readonly) NSArray *protocols;
@property (nonatomic, readonly) SEL setter;
@property (nonatomic, readonly) unsigned long long type;
@property (nonatomic, readonly) NSString *typeEncoding;

@end
