/* Generated by RuntimeBrowser
   Image: /var/containers/Bundle/Application/A77617CC-81F8-4D57-BCE6-77E8D969EEA1/UniqloWakeUp.app/Frameworks/PDebug.framework/PDebug
 */

@interface YYClassMethodInfo : NSObject {
    NSArray * _argumentTypeEncodings;
    int (* _imp;
    struct objc_method { } * _method;
    NSString * _name;
    NSString * _returnTypeEncoding;
    SEL  _sel;
    NSString * _typeEncoding;
}

@property (nonatomic, readonly) NSArray *argumentTypeEncodings;
@property (nonatomic, readonly) int (*imp;
@property (nonatomic, readonly) struct objc_method { }*method;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) NSString *returnTypeEncoding;
@property (nonatomic, readonly) SEL sel;
@property (nonatomic, readonly) NSString *typeEncoding;

@end
